class CfgPatches
{
	class TFV_Weapons_MG
	{
		units[]={};
		weapons[]=
		{
			"TFV_M73_SmartLink",
			"TFV_M73",
			"TFV_M247"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"OPTRE_Core",
			"A3_Weapons_F"
		};
		author="Article 2 Studios";
	};
};
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class MuzzleSlot;
class CowsSlot;
class PointerSlot;
class UnderBarrelSlot;
class CfgWeapons
{
	class optic_Aco;
	class InventoryOpticsItem_Base_F;
	class LMG_Mk200_F;
	class TFV_MachineGun_Base: LMG_Mk200_F
	{
		class WeaponSlotsInfo;
	};
	class TFV_M73_SmartLink: optic_Aco
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		displayName="[TFV] M73 Smart Link Scope";
		picture="\TFV_weapons\MG\icons\scope.paa";
		model="\TFV_Weapons\MG\M73_SmartLink.p3d";
		descriptionShort="M73 Smart-Linked Neural Interface Scope";
		weaponInfoType="RscWeaponZeroing";
		inertia=0.1;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=10;
			opticType=1;
			optics=1;
			modelOptics="\TFV_Weapons\MG\M73_SmartLink.p3d";
			class OpticsModes
			{
				class M73_IS
				{
					opticsID=1;
					useModelOptics=0;
					opticsPPEffects[]=
					{
						""
					};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.375;
					opticsZoomMax=0.55000001;
					opticsZoomInit=0.55000001;
					memoryPointCamera="opticView";
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					distanceZoomMin=300;
					distanceZoomMax=300;
				};
				class M73_Scope: M73_IS
				{
					opticsID=2;
					useModelOptics=1;
					opticsZoomMin=0.125;
					opticsZoomMax=0.052499998;
					opticsZoomInit=0.125;
					discretefov[]={0.125,0.052499998};
					discreteinitIndex=0;
					discreteDistance[]={100,300,400,500,600,700,800,900,1000};
					discreteDistanceInitIndex=1;
					distanceZoomMin=100;
					distanceZoomMax=1000;
					memoryPointCamera="opticView2";
					modelOptics[]=
					{
						"\TFV_Weapons\MG\MG_Optic_2x.p3d",
						"\TFV_Weapons\MG\MG_Optic_4x.p3d"
					};
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
				};
			};
		};
	};
	class TFV_M73: TFV_MachineGun_Base
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		scopeArsenal=2;
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\TFV_Weapons\MG\data\anim\OPTRE_M73_handanim.rtm",
			"Spartan_ManSkeleton",
			"\OPTRE_MJOLNIR\data\anims\OPTRE_anims\Weapons\M73_1_Spartan.rtm"
		};
		model="\TFV_Weapons\MG\M73.p3d";
		displayName="[TFV] M73 Light Machine Gun";
		descriptionShort="UNSC Light Machine Gun";
		picture="\TFV_Weapons\MG\icons\M73_1.paa";
		magazines[]=
		{
			"TFV_100Rnd_95x40_Box",
			"TFV_100Rnd_95x40_Box_Tracer",
			"TFV_100Rnd_95x40_Box_Tracer_Yellow",
			"TFV_200Rnd_95x40_Box",
			"TFV_200Rnd_95x40_Box_Tracer",
			"TFV_200Rnd_95x40_Box_Tracer_Yellow"
		};
		magazineWell[]={};
		reloadAction="GestureReloadM200";
		recoil="recoil_lim";
		baseWeapon="TFV_M73";
		cursor="OPTRE_M73";
		pictureWire="\TFV_Weapons\data\Pictures\WireWeaponIcons\Prime\MachineGun\MG_IRON.paa";
		ODST_1="OPTRE_ODST_HUD_AmmoCount_LMG";
		Glasses="OPTRE_GLASS_HUD_AmmoCount_LMG";
		Eye="OPTRE_EYE_HUD_AmmoCount_LMG";
		HUD_BulletInARows=4;
		HUD_TotalPosibleBullet=200;
		class GunParticles
		{
			class EffectShotCloud
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
			class MuzzleSlot: MuzzleSlot
			{
				compatibleitems[]=
				{
					"muzzle_snds_65_TI_blk_F",
					"TFV_MA5Suppressor"
				};
			};
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"optic_Nightstalker",
					"optic_tws",
					"optic_tws_mg",
					"optic_NVS",
					"optic_DMS",
					"optic_LRPS",
					"optic_ams",
					"optic_AMS_snd",
					"optic_AMS_khk",
					"optic_KHS_blk",
					"optic_KHS_tan",
					"optic_KHS_hex",
					"optic_KHS_old",
					"optic_SOS",
					"optic_MRCO",
					"optic_Arco",
					"optic_aco",
					"optic_ACO_grn",
					"optic_aco_smg",
					"optic_ACO_grn_smg",
					"optic_hamr",
					"optic_Holosight",
					"optic_Holosight_smg",
					"optic_Hamr_khk_F",
					"optic_SOS_khk_F",
					"optic_Arco_ghex_F",
					"optic_Arco_blk_F",
					"optic_DMS_ghex_F",
					"optic_ERCO_blk_F",
					"optic_ERCO_khk_F",
					"optic_ERCO_snd_F",
					"optic_LRPS_ghex_F",
					"optic_LRPS_tna_F",
					"optic_Holosight_blk_F",
					"optic_Holosight_khk_F",
					"optic_Holosight_smg_blk_F",
					"optic_Holosight_smg_khk_F",
					"TFV_M392_Scope",
					"TFV_BR55HB_Scope",
					"TFV_M7_Sight",
					"TFV_M393_Scope",
					"TFV_M393_ACOG",
					"TFV_M393_EOTECH",
					"TFV_M73_SmartLink",
					"TFV_BR45_Scope"
				};
			};
			class PointerSlot: PointerSlot
			{
				compatibleitems[]={};
			};
			class UnderBarrelSlot: UnderBarrelSlot
			{
				compatibleItems[]=
				{
					"bipod_01_F_blk",
					"bipod_02_F_blk",
					"bipod_03_F_blk"
				};
			};
		};
		modes[]=
		{
			"FullAuto",
			"Single",
			"close",
			"short",
			"medium",
			"far"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin3[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-03.ogg",
					"db8",
					1,
					2000
				};
				begin4[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-04.ogg",
					"db8",
					1,
					2000
				};
				begin5[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-05.ogg",
					"db8",
					1,
					2000
				};
				begin6[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-06.ogg",
					"db8",
					1,
					2000
				};
				begin7[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-07.ogg",
					"db8",
					1,
					2000
				};
				begin8[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-08.ogg",
					"db8",
					1,
					2000
				};
				begin9[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-09.ogg",
					"db8",
					1,
					2000
				};
				begin10[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-10.ogg",
					"db8",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin3",
					0.2,
					"begin4",
					0.1,
					"begin5",
					0.1,
					"begin6",
					0.1,
					"begin7",
					0.1,
					"begin8",
					0.1,
					"begin9",
					0.1,
					"begin10",
					0.1
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_trees",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_forest",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_meadows",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_houses",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_short_01",
					0.89125091,
					1,
					200
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_short_02",
					0.89125091,
					1,
					200
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_short_03",
					0.89125091,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin1",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_trees",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_forest",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_meadows",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_houses",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.078900002;
			dispersion=0.00075000001;
			minRange=2;
			minRangeProbab=0.0099999998;
			midRange=200;
			midRangeProbab=0.0099999998;
			maxRange=400;
			maxRangeProbab=0.0099999998;
		};
		class FullAuto: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin3[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-03.ogg",
					"db8",
					1,
					2000
				};
				begin4[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-04.ogg",
					"db8",
					1,
					2000
				};
				begin5[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-05.ogg",
					"db8",
					1,
					2000
				};
				begin6[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-06.ogg",
					"db8",
					1,
					2000
				};
				begin7[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-07.ogg",
					"db8",
					1,
					2000
				};
				begin8[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-08.ogg",
					"db8",
					1,
					2000
				};
				begin9[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-09.ogg",
					"db8",
					1,
					2000
				};
				begin10[]=
				{
					"\TFV_Weapons\MG\data\sounds\M73LMG-10.ogg",
					"db8",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin3",
					0.1,
					"begin4",
					0.1,
					"begin5",
					0.1,
					"begin6",
					0.1,
					"begin7",
					0.1,
					"begin8",
					0.1,
					"begin9",
					0.1,
					"begin10",
					0.1
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_trees",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_forest",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_meadows",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\MK200_tail_houses",
							1,
							1,
							1200
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_short_01",
					0.89125091,
					1,
					200
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_short_02",
					0.89125091,
					1,
					200
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_short_03",
					0.89125091,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin1",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_trees",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_forest",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_interior",
							1.9952624,
							1,
							1200
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_meadows",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Machineguns\Mk200\Silencer_Mk200_tail_houses",
							1,
							1,
							1800
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.078900002;
			dispersion=0.00075000001;
			minRange=2;
			minRangeProbab=0.0099999998;
			midRange=200;
			midRangeProbab=0.0099999998;
			maxRange=400;
			maxRangeProbab=0.0099999998;
		};
		class close: FullAuto
		{
			burst=10;
			aiRateOfFire=0.5;
			aiRateOfFireDistance=50;
			minRange=0;
			minRangeProbab=0.050000001;
			midRange=30;
			midRangeProbab=0.69999999;
			maxRange=50;
			maxRangeProbab=0.039999999;
			showToPlayer=0;
		};
		class short: close
		{
			burst=10;
			aiRateOfFire=2;
			aiRateOfFireDistance=300;
			minRange=50;
			minRangeProbab=0.050000001;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.039999999;
		};
		class medium: close
		{
			burst=10;
			aiRateOfFire=4;
			aiRateOfFireDistance=600;
			minRange=200;
			minRangeProbab=0.050000001;
			midRange=400;
			midRangeProbab=0.60000002;
			maxRange=600;
			maxRangeProbab=0.1;
		};
		class far: close
		{
			burst=10;
			aiRateOfFire=6;
			aiRateOfFireDistance=700;
			minRange=350;
			minRangeProbab=0.039999999;
			midRange=550;
			midRangeProbab=0.5;
			maxRange=700;
			maxRangeProbab=0.0099999998;
		};
		aiDispersionCoefY=10;
		aiDispersionCoefX=10;
	};
	class TFV_M247: TFV_M73
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		scopeArsenal=2;
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\TFV_Weapons\MG\data\anim\OPTRE_M247_handanim.rtm",
			"Spartan_ManSkeleton",
			"\OPTRE_MJOLNIR\data\anims\OPTRE_anims\Weapons\M247_Spartan.rtm"
		};
		model="\TFV_Weapons\MG\M247.p3d";
		displayName="[TFV] M247 General Purpose Machine Gun";
		descriptionShort="UNSC General Purpose Machine Gun";
		magazines[]=
		{
			"TFV_100Rnd_762x51_Box",
			"TFV_100Rnd_762x51_Box_Tracer",
			"TFV_100Rnd_762x51_Box_Tracer_Yellow",
			"TFV_400Rnd_762x51_Box_Tracer"
		};
		recoil="recoil_mk200";
		baseWeapon="TFV_M247";
		HUD_BulletInARows=2;
		HUD_TotalPosibleBullet=100;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=150;
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"optic_Nightstalker",
					"optic_tws",
					"optic_tws_mg",
					"optic_NVS",
					"optic_DMS",
					"optic_LRPS",
					"optic_ams",
					"optic_AMS_snd",
					"optic_AMS_khk",
					"optic_KHS_blk",
					"optic_KHS_tan",
					"optic_KHS_hex",
					"optic_KHS_old",
					"optic_SOS",
					"optic_MRCO",
					"optic_Arco",
					"optic_aco",
					"optic_ACO_grn",
					"optic_aco_smg",
					"optic_ACO_grn_smg",
					"optic_hamr",
					"optic_Holosight",
					"optic_Holosight_smg",
					"optic_Hamr_khk_F",
					"optic_SOS_khk_F",
					"optic_Arco_ghex_F",
					"optic_Arco_blk_F",
					"optic_DMS_ghex_F",
					"optic_ERCO_blk_F",
					"optic_ERCO_khk_F",
					"optic_ERCO_snd_F",
					"optic_LRPS_ghex_F",
					"optic_LRPS_tna_F",
					"optic_Holosight_blk_F",
					"optic_Holosight_khk_F",
					"optic_Holosight_smg_blk_F",
					"optic_Holosight_smg_khk_F",
					"TFV_M392_Scope",
					"TFV_BR55HB_Scope",
					"TFV_M7_Sight",
					"TFV_M393_Scope",
					"TFV_M393_ACOG",
					"TFV_M393_EOTECH",
					"TFV_BR45_Scope"
				};
			};
			class MuzzleSlot: MuzzleSlot
			{
				compatibleitems[]={};
			};
		};
		class Single: Single
		{
			class StandardSound: StandardSound
			{
				begin1[]=
				{
					"\TFV_Weapons\MG\data\sounds\M247_1.wss",
					1,
					1,
					2000
				};
				begin2[]=
				{
					"\TFV_Weapons\MG\data\sounds\M247_2.wss",
					1,
					1,
					2000
				};
			};
			reloadTime=0.082000002;
			dispersion=0.00075000001;
		};
		class FullAuto: FullAuto
		{
			class StandardSound: StandardSound
			{
				begin1[]=
				{
					"\TFV_Weapons\MG\data\sounds\M247_1.wss",
					1,
					1,
					2000
				};
				begin2[]=
				{
					"\TFV_Weapons\MG\data\sounds\M247_2.wss",
					1,
					1,
					2000
				};
			};
			reloadTime=0.082000002;
			dispersion=0.00075000001;
		};
	};
	class TFV_M73_AC: TFV_M73
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=1;
		scopeArsenal=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="TFV_M73_SmartLink";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="bipod_01_F_blk";
			};
		};
	};
	class TFV_M247_AC: TFV_M247
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=1;
		scopeArsenal=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="TFV_M393_ACOG";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="bipod_01_F_blk";
			};
		};
	};
};
