class CfgPatches
{
	class TFV_Weapons_AR
	{
		units[]={};
		weapons[]=
		{
			"TFV_MA5_SmartLink",
			"TFV_MA5Suppressor",
			"TFV_MA5B",
			"TFV_MA5BGL",
			"TFV_MA5C",
			"TFV_MA5CGL",
			"TFV_MA5A",
			"TFV_MA5AGL",
			"TFV_MA37",
			"TFV_MA37GL",
			"TFV_MA5K",
			"TFV_MA5C_SmartLink",
			"TFV_MA37B",
			"TFV_MA37BGL",
			"TFV_MA32",
			"TFV_MA32B",
			"TFV_MA32GL",
			"TFV_MA32BGL"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"OPTRE_Core",
			"OPTRE_Weapons",
			"A3_Weapons_F"
		};
		author="Article 2 Studios";
	};
};
class CfgMovesBasic
{
	class DefaultDie;
	class ManActions
	{
		GestureReloadMA5="GestureReloadMA5";
	};
	class Actions
	{
		class RifleBaseStandActions;
		class RifleAdjustProneBaseActions;
		class NoActions: ManActions
		{
			GestureReloadMA5[]=
			{
				"GestureReloadMA5",
				"Gesture"
			};
		};
		class RifleProneActions: RifleBaseStandActions
		{
			GestureReloadMA5[]=
			{
				"GestureReloadMA5_Prone",
				"gesture"
			};
		};
	};
};
class CfgGesturesMale
{
	class Default;
	class States
	{
		class GestureReloadMA5: Default
		{
			file="\OPTRE_Weapons\ar\Data\anim\MA5BReloadGesture.rtm";
			looped=0;
			speed=0.27000001;
			mask="handsWeapon";
			headBobStrength=0.1;
			headBobMode=2;
			rightHandIKBeg=1;
			rightHandIKEnd=1;
			leftHandIKCurve[]={0,1,0.050000001,0,0.94999999,0,1,1};
		};
		class GestureReloadMA5_Prone: Default
		{
			file="\OPTRE_Weapons\ar\Data\anim\MA5BReloadGesture_Prone.rtm";
			looped=0;
			speed=0.27000001;
			mask="handsWeapon";
			headBobStrength=0.1;
			headBobMode=2;
			rightHandIKBeg=1;
			rightHandIKEnd=1;
			leftHandIKCurve[]={0,1,0.050000001,0,0.94999999,0,1,1};
		};
	};
};
class CfgMovesBasicSevenFoot
{
	class DefaultDie;
	class ManActions
	{
		GestureReloadMA5="GestureReloadMA5";
	};
	class Actions
	{
		class RifleBaseStandActions;
		class RifleAdjustProneBaseActions;
		class NoActions: ManActions
		{
			GestureReloadMA5[]=
			{
				"GestureReloadMA5",
				"Gesture"
			};
		};
		class RifleProneActions: RifleBaseStandActions
		{
			GestureReloadMA5[]=
			{
				"GestureReloadMA5_Prone",
				"gesture"
			};
		};
	};
};
class CfgGesturesSevenFoot
{
	class Default;
	class GestureReloadBase;
	class States
	{
		class GestureReloadMA5: Default
		{
			file="\OPTRE_Weapons\ar\Data\anim\MA5BReloadGesture_Spartan.rtm";
			looped=0;
			speed=0.27000001;
			mask="handsWeapon";
			headBobStrength=0.1;
			headBobMode=2;
			rightHandIKBeg=1;
			rightHandIKEnd=1;
			leftHandIKCurve[]={0,1,0.050000001,0,0.94999999,0,1,1};
		};
		class GestureReloadMA5_Prone: Default
		{
			file="\OPTRE_Weapons\ar\Data\anim\MA5BReloadGesture_Spartan.rtm";
			looped=0;
			speed=0.27000001;
			mask="handsWeapon";
			headBobStrength=0.1;
			headBobMode=2;
			rightHandIKBeg=1;
			rightHandIKEnd=1;
			leftHandIKCurve[]={0,1,0.050000001,0,0.94999999,0,1,1};
		};
	};
};
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class MuzzleSlot;
class CowsSlot;
class PointerSlot;
class UnderBarrelSlot;
class CfgWeapons
{
	class optic_Aco;
	class InventoryOpticsItem_Base_F;
	class arifle_Mk20_F;
	class muzzle_snds_H;
	class TFV_Rifle_Base: arifle_Mk20_F
	{
		class WeaponSlotsInfo;
	};
	class UGL_F;
	class TFV_MA5_SmartLink: optic_Aco
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		displayName="[TFV] MA5B Smart Link Zoom Enhancement";
		model="\OPTRE_Weapons\AR\MA5_smartlink.p3d";
		descriptionShort="Smart Link Optic For MA5B";
		weaponInfoType="RscWeaponZeroing";
		scope=2;
		scopeArsenal=2;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=1;
			opticType=1;
			optics=1;
			modelOptics="\OPTRE_Weapons\AR\MA5_smartlink.p3d";
			inertia=0.1;
			class OpticsModes
			{
				class TFV_MA5_Smart
				{
					opticsID=1;
					useModelOptics=0;
					opticsPPEffects[]=
					{
						""
					};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.375;
					opticsZoomMax=1.1;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					visionMode[]={};
					distanceZoomMin=400;
					distanceZoomMax=400;
					cameraDir="";
				};
				class TFV_MA5_SmartZoom: TFV_MA5_Smart
				{
					opticsID=2;
					opticsZoomMin=0.12141;
					opticsZoomMax=0.12141;
					opticsZoomInit=0.12141;
				};
			};
		};
	};
	class TFV_MA37_Smartlink_Scope: optic_Aco
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		displayName="[TFV] 2x Smart Link Scope";
		descriptionShort="2x Smart Linked Scope";
		model="OPTRE_Weapons\AR\MA37_2x_Scope.p3d";
		inertia=0.1;
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=4;
			modelOptics="\A3\Weapons_F\empty";
			optics=1;
			class OpticsModes
			{
				class MA37_Irons
				{
					opticsID=2;
					useModelOptics=0;
					opticsPPEffects[]=
					{
						""
					};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.375;
					opticsZoomMax=1;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					visionMode[]={};
					distanceZoomMin=400;
					distanceZoomMax=400;
				};
				class MA37_Sight
				{
					opticsID=1;
					useModelOptics=1;
					modelOptics[]=
					{
						"\OPTRE_Weapons\AR\MA37_2x_Scope.p3d"
					};
					opticsPPEffects[]=
					{
						"OpticsCHAbera2",
						"OpticsBlur2"
					};
					opticsFlare=1;
					opticsDisablePeripherialVision=1;
					opticsZoomMin=0.125;
					opticsZoomMax=0.125;
					opticsZoomInit=0.75;
					discretefov[]={0.07};
					discreteInitIndex=0;
					memoryPointCamera="opticView";
					visionMode[]=
					{
						"Normal",
						"NVG"
					};
					distanceZoomMin=400;
					distanceZoomMax=400;
				};
			};
		};
	};
	class TFV_MA5C_SmartLink: TFV_MA5_SmartLink
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		displayName="[TFV] MA5C Smart Link Zoom Enhancement";
		model="\OPTRE_Weapons\AR\MA5C_smartlink.p3d";
		descriptionShort="Smart Link Optic For MA5C";
		scope=2;
		scopeArsenal=2;
		class ItemInfo: ItemInfo
		{
			modelOptics="\OPTRE_Weapons\AR\MA5C_smartlink.p3d";
		};
	};
	class TFV_MA5_BUIS: optic_Aco
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		displayName="[TFV] MA5 Alternate Ironsights";
		model="\OPTRE_Weapons\AR\MA5_irons.p3d";
		descriptionShort="Alternate Ironsights For MA5 Rifles";
		weaponInfoType="RscWeaponZeroing";
		class ItemInfo: InventoryOpticsItem_Base_F
		{
			mass=1;
			opticType=1;
			optics=1;
			modelOptics="\OPTRE_Weapons\AR\MA5_irons.p3d";
			inertia=0.1;
			class OpticsModes
			{
				class TFV_MA5_Smart
				{
					opticsID=1;
					useModelOptics=0;
					opticsPPEffects[]=
					{
						""
					};
					opticsFlare=0;
					opticsDisablePeripherialVision=0;
					opticsZoomMin=0.375;
					opticsZoomMax=1.1;
					opticsZoomInit=0.75;
					memoryPointCamera="eye";
					visionMode[]={};
					distanceZoomMin=100;
					distanceZoomMax=900;
					cameraDir="";
				};
			};
		};
	};
	class TFV_MA5Suppressor: muzzle_snds_H
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		scopeArsenal=2;
		displayName="UNSC Suppressor";
		model="OPTRE_Weapons\ar\MA5Suppressor.p3d";
		picture="\a3\Weapons_F_Exp\Acc\Data\UI\icon_muzzle_snds_65_ti_blk_f_ca.paa";
	};
	class TFV_MA5B: TFV_Rifle_Base
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		scopeArsenal=2;
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\OPTRE_Weapons\AR\data\anim\hand_anim_ma5c.rtm",
			"Spartan_ManSkeleton",
			"\OPTRE_MJOLNIR\data\anims\OPTRE_anims\Weapons\ma5a_handanim_Spartan.rtm"
		};
		model="\OPTRE_Weapons\AR\MA5B.p3d";
		displayName="$STR_OPTRE_Weapons_MA5B_displayName";
		descriptionShort="UNSC Assault Rifle";
		magazines[]=
		{
			"TFV_60Rnd_762x51_Mag",
			"TFV_60Rnd_762x51_Mag_Tracer",
			"TFV_60Rnd_762x51_Mag_Tracer_Yellow"
		};
		magazineWell[]={};
		reloadAction="GestureReloadMA5";
		baseWeapon="TFV_MA5B";
		recoil="recoil_trg21";
		cursor="OPTRE_MA5";
		picture="\OPTRE_Weapons\ar\icons\ar_a.paa";
		pictureWire="\OPTRE_Weapons\data\Pictures\WireWeaponIcons\Prime\AssaultRifle\AR.paa";
		ODST_1="OPTRE_ODST_HUD_AmmoCount_AR";
		Glasses="OPTRE_GLASS_HUD_AmmoCount_AR";
		Eye="OPTRE_EYE_HUD_AmmoCount_AR";
		HUD_BulletInARows=2;
		HUD_TotalPosibleBullet=60;
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"OPTRE_Weapons\ar\data\weapon_co.paa",
			"OPTRE_Weapons\ar\data\smartlink_co.paa"
		};
		class FlashLight
		{
			color[]={180,160,130};
			ambient[]={0.89999998,0.80000001,0.69999999};
			intensity=100;
			size=1;
			innerAngle=5;
			outerAngle=100;
			coneFadeCoef=10;
			position="flash dir";
			direction="flash";
			useFlare=1;
			flareSize=1.5;
			flareMaxDistance=100;
			dayLight=0;
			class Attenuation
			{
				start=0;
				constant=0.5;
				linear=0.1;
				quadratic=0.2;
				hardLimitStart=27;
				hardLimitEnd=34;
			};
			scale[]={0};
		};
		class GunParticles
		{
			class EffectShotCloud
			{
				positionName="Nabojnicestart";
				directionName="Nabojniceend";
				effectName="CaselessAmmoCloud";
			};
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=60;
			class MuzzleSlot: MuzzleSlot
			{
				compatibleitems[]=
				{
					"muzzle_snds_65_TI_blk_F",
					"TFV_MA5Suppressor"
				};
			};
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"optic_Nightstalker",
					"optic_tws",
					"optic_tws_mg",
					"optic_NVS",
					"optic_DMS",
					"optic_LRPS",
					"optic_ams",
					"optic_AMS_snd",
					"optic_AMS_khk",
					"optic_KHS_blk",
					"optic_KHS_tan",
					"optic_KHS_hex",
					"optic_KHS_old",
					"optic_SOS",
					"optic_MRCO",
					"optic_Arco",
					"optic_aco",
					"optic_ACO_grn",
					"optic_aco_smg",
					"optic_ACO_grn_smg",
					"optic_hamr",
					"optic_Holosight",
					"optic_Holosight_smg",
					"optic_Hamr_khk_F",
					"optic_SOS_khk_F",
					"optic_Arco_ghex_F",
					"optic_Arco_blk_F",
					"optic_DMS_ghex_F",
					"optic_ERCO_blk_F",
					"optic_ERCO_khk_F",
					"optic_ERCO_snd_F",
					"optic_LRPS_ghex_F",
					"optic_LRPS_tna_F",
					"optic_Holosight_blk_F",
					"optic_Holosight_khk_F",
					"optic_Holosight_smg_blk_F",
					"optic_Holosight_smg_khk_F",
					"TFV_M392_Scope",
					"TFV_BR55HB_Scope",
					"TFV_M7_Sight",
					"TFV_M393_Scope",
					"TFV_M393_ACOG",
					"TFV_M393_EOTECH",
					"TFV_MA5_BUIS",
					"TFV_MA5_SmartLink",
					"TFV_MA5C_SmartLink",
					"TFV_BR45_Scope"
				};
			};
			class PointerSlot: PointerSlot
			{
				compatibleitems[]=
				{
					"acc_pointer_IR"
				};
			};
			class UnderBarrelSlot: UnderBarrelSlot
			{
				compatibleitems[]={};
			};
		};
		modes[]=
		{
			"FullAuto",
			"Single",
			"close",
			"short",
			"medium",
			"far"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B1.ogg",
					"db10",
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B2.ogg",
					"db10",
					1,
					2000
				};
				begin3[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B3.ogg",
					"db10",
					1,
					2000
				};
				begin4[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B4.ogg",
					"db10",
					1,
					2000
				};
				begin5[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B5.ogg",
					"db10",
					1,
					2000
				};
				begin6[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B6.ogg",
					"db10",
					1,
					2000
				};
				begin7[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B7.ogg",
					"db10",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.16,
					"begin2",
					0.14,
					"begin3",
					0.14,
					"begin4",
					0.14,
					"begin5",
					0.14,
					"begin6",
					0.14,
					"begin7",
					0.14
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_trees",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_forest",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_interior",
							1.5848932,
							1,
							1400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_meadows",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_houses",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.066699997;
			dispersion=0.00075000001;
			recoil="recoil_single_trg";
			recoilProne="recoil_single_prone_trg";
			minRange=2;
			minRangeProbab=0.0099999998;
			midRange=200;
			midRangeProbab=0.0099999998;
			maxRange=400;
			maxRangeProbab=0.0099999998;
		};
		class FullAuto: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B1.ogg",
					"db10",
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B2.ogg",
					"db10",
					1,
					2000
				};
				begin3[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B3.ogg",
					"db10",
					1,
					2000
				};
				begin4[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B4.ogg",
					"db10",
					1,
					2000
				};
				begin5[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B5.ogg",
					"db10",
					1,
					2000
				};
				begin6[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B6.ogg",
					"db10",
					1,
					2000
				};
				begin7[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5B7.ogg",
					"db10",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.16,
					"begin2",
					0.14,
					"begin3",
					0.14,
					"begin4",
					0.14,
					"begin5",
					0.14,
					"begin6",
					0.14,
					"begin7",
					0.14
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_trees",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_forest",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_interior",
							1.5848932,
							1,
							1400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_meadows",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_houses",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.066699997;
			dispersion=0.00085000001;
			recoil="recoil_auto_trg";
			recoilProne="recoil_auto_prone_trg";
			minRange=2;
			minRangeProbab=0.0099999998;
			midRange=200;
			midRangeProbab=0.0099999998;
			maxRange=400;
			maxRangeProbab=0.0099999998;
		};
		class close: FullAuto
		{
			burst=10;
			aiRateOfFire=0.5;
			aiRateOfFireDistance=50;
			minRange=0;
			minRangeProbab=0.050000001;
			midRange=30;
			midRangeProbab=0.69999999;
			maxRange=50;
			maxRangeProbab=0.039999999;
			showToPlayer=0;
		};
		class short: close
		{
			burst=8;
			aiRateOfFire=2;
			aiRateOfFireDistance=300;
			minRange=50;
			minRangeProbab=0.050000001;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.039999999;
		};
		class medium: close
		{
			burst=5;
			aiRateOfFire=4;
			aiRateOfFireDistance=600;
			minRange=200;
			minRangeProbab=0.050000001;
			midRange=400;
			midRangeProbab=0.60000002;
			maxRange=600;
			maxRangeProbab=0.1;
		};
		class far: close
		{
			burst=3;
			aiRateOfFire=6;
			aiRateOfFireDistance=700;
			minRange=350;
			minRangeProbab=0.039999999;
			midRange=550;
			midRangeProbab=0.5;
			maxRange=700;
			maxRangeProbab=0.0099999998;
		};
		aiDispersionCoefY=10;
		aiDispersionCoefX=10;
	};
	class TFV_MA5BGL: TFV_MA5B
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		model="\OPTRE_Weapons\AR\MA5BGL.p3d";
		displayName="[TFV] MA5B + M301 GL Assault Rifle";
		descriptionShort="UNSC Assault Rifle + GL";
		picture="\OPTRE_Weapons\ar\icons\argl_a.paa";
		muzzles[]=
		{
			"this",
			"TFV_M301UGL"
		};
		baseWeapon="TFV_MA5BGL";
		pictureWire="\OPTRE_Weapons\data\Pictures\WireWeaponIcons\Prime\AssaultRifle\AR_UGL.paa";
		class TFV_M301UGL: UGL_F
		{
			displayName="[TFV] M301 Grenade Launcher";
			descriptionShort="M301 GL";
			cursor="EmptyCursor";
			cursorAim="TFV_GRNDLNCH";
			useModelOptics=0;
			useExternalOptic=0;
			cameraDir="OP_look";
			discreteDistance[]={100,200,300};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3"
			};
			discreteDistanceInitIndex=0;
			reloadAction="GestureReloadMXUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"UGL_FlareWhite_F",
				"UGL_FlareGreen_F",
				"UGL_FlareRed_F",
				"UGL_FlareYellow_F",
				"UGL_FlareCIR_F",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"3Rnd_HE_Grenade_shell",
				"3Rnd_UGL_FlareWhite_F",
				"3Rnd_UGL_FlareGreen_F",
				"3Rnd_UGL_FlareRed_F",
				"3Rnd_UGL_FlareYellow_F",
				"3Rnd_UGL_FlareCIR_F",
				"3Rnd_Smoke_Grenade_shell",
				"3Rnd_SmokeRed_Grenade_shell",
				"3Rnd_SmokeGreen_Grenade_shell",
				"3Rnd_SmokeYellow_Grenade_shell",
				"3Rnd_SmokePurple_Grenade_shell",
				"3Rnd_SmokeBlue_Grenade_shell",
				"3Rnd_SmokeOrange_Grenade_shell"
			};
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class PointerSlot: PointerSlot
			{
				compatibleitems[]=
				{
					"acc_pointer_IR",
					"acc_flashlight"
				};
			};
		};
		class FlashLight
		{
		};
	};
	class TFV_MA5C: TFV_MA5B
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		model="\OPTRE_Weapons\AR\MA5C.p3d";
		displayName="[TFV] MA5C ICWS Assault Rifle";
		magazines[]=
		{
			"TFV_32Rnd_762x51_Mag",
			"TFV_32Rnd_762x51_Mag_Tracer",
			"TFV_32Rnd_762x51_Mag_Tracer_Yellow"
		};
		baseWeapon="TFV_MA5C";
		HUD_TotalPosibleBullet=32;
		modes[]=
		{
			"Single",
			"FullAuto",
			"close",
			"short",
			"medium",
			"far"
		};
		class Single: Single
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
					"db5",
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
					"db5",
					1,
					2000
				};
				begin3[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
					"db5",
					1,
					2000
				};
				begin4[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
					"db5",
					1,
					2000
				};
				begin5[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
					"db5",
					1,
					2000
				};
				begin6[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
					"db5",
					1,
					2000
				};
				begin7[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
					"db5",
					1,
					2000
				};
				begin8[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
					"db5",
					1,
					2000
				};
				begin9[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
					"db5",
					1,
					2000
				};
				begin10[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
					"db5",
					1,
					2000
				};
				begin11[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
					"db5",
					1,
					2000
				};
				begin12[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
					"db5",
					1,
					2000
				};
				begin13[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
					"db5",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.07,
					"begin2",
					0.07,
					"begin3",
					0.07,
					"begin4",
					0.07,
					"begin5",
					0.07,
					"begin6",
					0.07,
					"begin7",
					0.07,
					"begin8",
					0.07,
					"begin9",
					0.07,
					"begin10",
					0.07,
					"begin11",
					0.07,
					"begin12",
					0.07,
					"begin13",
					0.090000004
				};
			};
			reloadTime=0.092307694;
		};
		class FullAuto: FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
					"db5",
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
					"db5",
					1,
					2000
				};
				begin3[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
					"db5",
					1,
					2000
				};
				begin4[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
					"db5",
					1,
					2000
				};
				begin5[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
					"db5",
					1,
					2000
				};
				begin6[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
					"db5",
					1,
					2000
				};
				begin7[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
					"db5",
					1,
					2000
				};
				begin8[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
					"db5",
					1,
					2000
				};
				begin9[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
					"db5",
					1,
					2000
				};
				begin10[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
					"db5",
					1,
					2000
				};
				begin11[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
					"db5",
					1,
					2000
				};
				begin12[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
					"db5",
					1,
					2000
				};
				begin13[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
					"db5",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.07,
					"begin2",
					0.07,
					"begin3",
					0.07,
					"begin4",
					0.07,
					"begin5",
					0.07,
					"begin6",
					0.07,
					"begin7",
					0.07,
					"begin8",
					0.07,
					"begin9",
					0.07,
					"begin10",
					0.07,
					"begin11",
					0.07,
					"begin12",
					0.07,
					"begin13",
					0.090000004
				};
			};
			reloadTime=0.092307694;
		};
		class close: FullAuto
		{
			burst=5;
			aiRateOfFire=0.5;
			aiRateOfFireDistance=50;
			minRange=0;
			minRangeProbab=0.050000001;
			midRange=30;
			midRangeProbab=0.69999999;
			maxRange=50;
			maxRangeProbab=0.039999999;
			showToPlayer=0;
		};
		class short: close
		{
			burst=3;
			aiRateOfFire=2;
			aiRateOfFireDistance=300;
			minRange=50;
			minRangeProbab=0.050000001;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.039999999;
		};
		class medium: close
		{
			burst=2;
			aiRateOfFire=4;
			aiRateOfFireDistance=600;
			minRange=200;
			minRangeProbab=0.050000001;
			midRange=400;
			midRangeProbab=0.60000002;
			maxRange=600;
			maxRangeProbab=0.1;
		};
		class far: close
		{
			burst=1;
			aiRateOfFire=6;
			aiRateOfFireDistance=700;
			minRange=350;
			minRangeProbab=0.039999999;
			midRange=550;
			midRangeProbab=0.5;
			maxRange=700;
			maxRangeProbab=0.0099999998;
		};
	};
	class TFV_MA5CGL: TFV_MA5BGL
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		model="\OPTRE_Weapons\AR\MA5CGL.p3d";
		displayName="[TFV] MA5C + M301 GL Assault Rifle";
		magazines[]=
		{
			"TFV_32Rnd_762x51_Mag",
			"TFV_32Rnd_762x51_Mag_Tracer",
			"TFV_32Rnd_762x51_Mag_Tracer_Yellow"
		};
		baseWeapon="TFV_MA5CGL";
		HUD_TotalPosibleBullet=32;
		modes[]=
		{
			"Single",
			"FullAuto",
			"close",
			"short",
			"medium",
			"far"
		};
		class Single: Single
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
					"db5",
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
					"db5",
					1,
					2000
				};
				begin3[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
					"db5",
					1,
					2000
				};
				begin4[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
					"db5",
					1,
					2000
				};
				begin5[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
					"db5",
					1,
					2000
				};
				begin6[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
					"db5",
					1,
					2000
				};
				begin7[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
					"db5",
					1,
					2000
				};
				begin8[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
					"db5",
					1,
					2000
				};
				begin9[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
					"db5",
					1,
					2000
				};
				begin10[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
					"db5",
					1,
					2000
				};
				begin11[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
					"db5",
					1,
					2000
				};
				begin12[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
					"db5",
					1,
					2000
				};
				begin13[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
					"db5",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.07,
					"begin2",
					0.07,
					"begin3",
					0.07,
					"begin4",
					0.07,
					"begin5",
					0.07,
					"begin6",
					0.07,
					"begin7",
					0.07,
					"begin8",
					0.07,
					"begin9",
					0.07,
					"begin10",
					0.07,
					"begin11",
					0.07,
					"begin12",
					0.07,
					"begin13",
					0.090000004
				};
			};
			reloadTime=0.092307694;
		};
		class FullAuto: FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-01.ogg",
					"db5",
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-02.ogg",
					"db5",
					1,
					2000
				};
				begin3[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-03.ogg",
					"db5",
					1,
					2000
				};
				begin4[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-04.ogg",
					"db5",
					1,
					2000
				};
				begin5[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-05.ogg",
					"db5",
					1,
					2000
				};
				begin6[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-06.ogg",
					"db5",
					1,
					2000
				};
				begin7[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-07.ogg",
					"db5",
					1,
					2000
				};
				begin8[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-08.ogg",
					"db5",
					1,
					2000
				};
				begin9[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-09.ogg",
					"db5",
					1,
					2000
				};
				begin10[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-10.ogg",
					"db5",
					1,
					2000
				};
				begin11[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-11.ogg",
					"db5",
					1,
					2000
				};
				begin12[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-12.ogg",
					"db5",
					1,
					2000
				};
				begin13[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5C-13.ogg",
					"db5",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.07,
					"begin2",
					0.07,
					"begin3",
					0.07,
					"begin4",
					0.07,
					"begin5",
					0.07,
					"begin6",
					0.07,
					"begin7",
					0.07,
					"begin8",
					0.07,
					"begin9",
					0.07,
					"begin10",
					0.07,
					"begin11",
					0.07,
					"begin12",
					0.07,
					"begin13",
					0.090000004
				};
			};
			reloadTime=0.092307694;
		};
		class close: FullAuto
		{
			burst=5;
			aiRateOfFire=0.5;
			aiRateOfFireDistance=50;
			minRange=0;
			minRangeProbab=0.050000001;
			midRange=30;
			midRangeProbab=0.69999999;
			maxRange=50;
			maxRangeProbab=0.039999999;
			showToPlayer=0;
		};
		class short: close
		{
			burst=3;
			aiRateOfFire=2;
			aiRateOfFireDistance=300;
			minRange=50;
			minRangeProbab=0.050000001;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.039999999;
		};
		class medium: close
		{
			burst=2;
			aiRateOfFire=4;
			aiRateOfFireDistance=600;
			minRange=200;
			minRangeProbab=0.050000001;
			midRange=400;
			midRangeProbab=0.60000002;
			maxRange=600;
			maxRangeProbab=0.1;
		};
		class far: close
		{
			burst=1;
			aiRateOfFire=6;
			aiRateOfFireDistance=700;
			minRange=350;
			minRangeProbab=0.039999999;
			midRange=550;
			midRangeProbab=0.5;
			maxRange=700;
			maxRangeProbab=0.0099999998;
		};
	};
	class TFV_MA5A: TFV_MA5C
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		model="\OPTRE_Weapons\AR\MA5A.p3d";
		displayName="[TFV] MA3A ICWS Assault Rifle";
		baseWeapon="TFV_MA5A";
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=55;
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"optic_Nightstalker",
					"optic_tws",
					"optic_tws_mg",
					"optic_NVS",
					"optic_DMS",
					"optic_LRPS",
					"optic_ams",
					"optic_AMS_snd",
					"optic_AMS_khk",
					"optic_KHS_blk",
					"optic_KHS_tan",
					"optic_KHS_hex",
					"optic_KHS_old",
					"optic_SOS",
					"optic_MRCO",
					"optic_Arco",
					"optic_aco",
					"optic_ACO_grn",
					"optic_aco_smg",
					"optic_ACO_grn_smg",
					"optic_hamr",
					"optic_Holosight",
					"optic_Holosight_smg",
					"optic_Hamr_khk_F",
					"optic_SOS_khk_F",
					"optic_Arco_ghex_F",
					"optic_Arco_blk_F",
					"optic_DMS_ghex_F",
					"optic_ERCO_blk_F",
					"optic_ERCO_khk_F",
					"optic_ERCO_snd_F",
					"optic_LRPS_ghex_F",
					"optic_LRPS_tna_F",
					"optic_Holosight_blk_F",
					"optic_Holosight_khk_F",
					"optic_Holosight_smg_blk_F",
					"optic_Holosight_smg_khk_F",
					"TFV_M392_Scope",
					"TFV_BR55HB_Scope",
					"TFV_M7_Sight",
					"TFV_M393_Scope",
					"TFV_M393_ACOG",
					"TFV_M393_EOTECH",
					"TFV_BR45_Scope"
				};
			};
		};
	};
	class TFV_MA5AGL: TFV_MA5CGL
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		model="\OPTRE_Weapons\AR\MA5AGL.p3d";
		displayName="[TFV] MA3A + M301 GL Assault Rifle";
		baseWeapon="TFV_MA5AGL";
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=55;
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"optic_Nightstalker",
					"optic_tws",
					"optic_tws_mg",
					"optic_NVS",
					"optic_DMS",
					"optic_LRPS",
					"optic_ams",
					"optic_AMS_snd",
					"optic_AMS_khk",
					"optic_KHS_blk",
					"optic_KHS_tan",
					"optic_KHS_hex",
					"optic_KHS_old",
					"optic_SOS",
					"optic_MRCO",
					"optic_Arco",
					"optic_aco",
					"optic_ACO_grn",
					"optic_aco_smg",
					"optic_ACO_grn_smg",
					"optic_hamr",
					"optic_Holosight",
					"optic_Holosight_smg",
					"optic_Hamr_khk_F",
					"optic_SOS_khk_F",
					"optic_Arco_ghex_F",
					"optic_Arco_blk_F",
					"optic_DMS_ghex_F",
					"optic_ERCO_blk_F",
					"optic_ERCO_khk_F",
					"optic_ERCO_snd_F",
					"optic_LRPS_ghex_F",
					"optic_LRPS_tna_F",
					"optic_Holosight_blk_F",
					"optic_Holosight_khk_F",
					"optic_Holosight_smg_blk_F",
					"optic_Holosight_smg_khk_F",
					"TFV_M392_Scope",
					"TFV_BR55HB_Scope",
					"TFV_M7_Sight",
					"TFV_M393_Scope",
					"TFV_M393_ACOG",
					"TFV_M393_EOTECH",
					"TFV_BR45_Scope"
				};
			};
		};
	};
	class TFV_MA37: TFV_MA5C
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\OPTRE_Weapons\AR\data\anim\hand_anim_ma37.rtm",
			"Spartan_ManSkeleton",
			"\OPTRE_MJOLNIR\data\anims\OPTRE_anims\Weapons\hand_anim_ma37_Spartan.rtm"
		};
		model="\OPTRE_Weapons\AR\MA37.p3d";
		displayName="[TFV] MA37 ICWS Assault Rifle";
		maxZeroing=400;
		discreteDistance[]={400};
		baseWeapon="TFV_MA37";
		cursor="OPTRE_MA37";
		pictureWire="\OPTRE_Weapons\data\Pictures\WireWeaponIcons\Prime\AssaultRifle\37.paa";
		modes[]=
		{
			"FullAuto",
			"Single",
			"close",
			"short",
			"medium",
			"far"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\AssaultRifle_1.wss",
					1,
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\AssaultRifle_2.wss",
					1,
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.34,
					"begin2",
					0.33000001
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_trees",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_forest",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_interior",
							1.5848932,
							1,
							1400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_meadows",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_houses",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.092307694;
			dispersion=0.00075000001;
			recoil="recoil_single_trg";
			recoilProne="recoil_single_prone_trg";
			minRange=2;
			minRangeProbab=0.0099999998;
			midRange=200;
			midRangeProbab=0.0099999998;
			maxRange=400;
			maxRangeProbab=0.0099999998;
		};
		class FullAuto: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\AssaultRifle_1.wss",
					1,
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\AssaultRifle_2.wss",
					1,
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.34,
					"begin2",
					0.33000001
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_trees",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_forest",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_interior",
							1.5848932,
							1,
							1400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_meadows",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_houses",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.092307694;
			dispersion=0.00085000001;
			recoil="recoil_auto_trg";
			recoilProne="recoil_auto_prone_trg";
			minRange=2;
			minRangeProbab=0.0099999998;
			midRange=200;
			midRangeProbab=0.0099999998;
			maxRange=400;
			maxRangeProbab=0.0099999998;
		};
		class close: FullAuto
		{
			burst=10;
			aiRateOfFire=0.5;
			aiRateOfFireDistance=50;
			minRange=0;
			minRangeProbab=0.050000001;
			midRange=30;
			midRangeProbab=0.69999999;
			maxRange=50;
			maxRangeProbab=0.039999999;
			showToPlayer=0;
		};
		class short: close
		{
			burst=8;
			aiRateOfFire=2;
			aiRateOfFireDistance=300;
			minRange=50;
			minRangeProbab=0.050000001;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.039999999;
		};
		class medium: close
		{
			burst=5;
			aiRateOfFire=4;
			aiRateOfFireDistance=600;
			minRange=200;
			minRangeProbab=0.050000001;
			midRange=400;
			midRangeProbab=0.60000002;
			maxRange=600;
			maxRangeProbab=0.1;
		};
		class far: close
		{
			burst=3;
			aiRateOfFire=6;
			aiRateOfFireDistance=700;
			minRange=350;
			minRangeProbab=0.039999999;
			midRange=550;
			midRangeProbab=0.5;
			maxRange=700;
			maxRangeProbab=0.0099999998;
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"TFV_MA37_Smartlink_Scope"
				};
			};
			class PointerSlot: PointerSlot
			{
				compatibleitems[]={};
			};
		};
	};
	class TFV_MA37B: TFV_MA37
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		displayName="[TFV] MA40 ICWS Assault Rifle";
		model="\OPTRE_Weapons\AR\MA37B.p3d";
		baseWeapon="TFV_MA37B";
		magazines[]=
		{
			"TFV_32Rnd_762x51_Mag",
			"TFV_32Rnd_762x51_Mag_Tracer",
			"TFV_32Rnd_762x51_Mag_Tracer_Yellow"
		};
	};
	class TFV_MA37GL: TFV_MA5CGL
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\OPTRE_Weapons\AR\data\anim\hand_anim_ma37.rtm",
			"Spartan_ManSkeleton",
			"\OPTRE_MJOLNIR\data\anims\OPTRE_anims\Weapons\hand_anim_ma37_Spartan.rtm"
		};
		model="\OPTRE_Weapons\AR\MA37GL.p3d";
		displayName="[TFV] MA37 + M301 GL Assault Rifle";
		maxZeroing=400;
		discreteDistance[]={400};
		baseWeapon="TFV_MA37GL";
		cursor="OPTRE_MA37";
		pictureWire="\OPTRE_Weapons\data\Pictures\WireWeaponIcons\Prime\AssaultRifle\37_UGL.paa";
		modes[]=
		{
			"FullAuto",
			"Single",
			"close",
			"short",
			"medium",
			"far"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\AssaultRifle_1.wss",
					1,
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\AssaultRifle_2.wss",
					1,
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.34,
					"begin2",
					0.33000001
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_trees",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_forest",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_interior",
							1.5848932,
							1,
							1400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_meadows",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_houses",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.092307694;
			dispersion=0.00075000001;
			recoil="recoil_single_trg";
			recoilProne="recoil_single_prone_trg";
			minRange=2;
			minRangeProbab=0.0099999998;
			midRange=200;
			midRangeProbab=0.0099999998;
			maxRange=400;
			maxRangeProbab=0.0099999998;
		};
		class FullAuto: Mode_FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\AssaultRifle_1.wss",
					1,
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\AssaultRifle_2.wss",
					1,
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.34,
					"begin2",
					0.33000001
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_trees",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_forest",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_interior",
							1.5848932,
							1,
							1400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_meadows",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\TRG20_tail_houses",
							1,
							1,
							1400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			class SilencedSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_01",
					1,
					1,
					400
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_02",
					1,
					1,
					400
				};
				begin3[]=
				{
					"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_short_03",
					1,
					1,
					400
				};
				soundBegin[]=
				{
					"begin1",
					0.33000001,
					"begin2",
					0.33000001,
					"begin3",
					0.34
				};
				class SoundTails
				{
					class TailTrees
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_trees",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*trees";
					};
					class TailForest
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_forest",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*forest";
					};
					class TailInterior
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_tail_interior",
							1,
							1,
							400
						};
						frequency=1;
						volume="interior";
					};
					class TailMeadows
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_meadows",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*(meadows/2 max sea/2)";
					};
					class TailHouses
					{
						sound[]=
						{
							"A3\Sounds_F\arsenal\weapons\Rifles\TRG20\Silencer_TRG20_Tail_houses",
							1,
							1,
							400
						};
						frequency=1;
						volume="(1-interior/1.4)*houses";
					};
				};
			};
			reloadTime=0.092307694;
			dispersion=0.00085000001;
			recoil="recoil_auto_trg";
			recoilProne="recoil_auto_prone_trg";
			minRange=2;
			minRangeProbab=0.0099999998;
			midRange=200;
			midRangeProbab=0.0099999998;
			maxRange=400;
			maxRangeProbab=0.0099999998;
		};
		class close: FullAuto
		{
			burst=10;
			aiRateOfFire=0.5;
			aiRateOfFireDistance=50;
			minRange=0;
			minRangeProbab=0.050000001;
			midRange=30;
			midRangeProbab=0.69999999;
			maxRange=50;
			maxRangeProbab=0.039999999;
			showToPlayer=0;
		};
		class short: close
		{
			burst=8;
			aiRateOfFire=2;
			aiRateOfFireDistance=300;
			minRange=50;
			minRangeProbab=0.050000001;
			midRange=150;
			midRangeProbab=0.69999999;
			maxRange=300;
			maxRangeProbab=0.039999999;
		};
		class medium: close
		{
			burst=5;
			aiRateOfFire=4;
			aiRateOfFireDistance=600;
			minRange=200;
			minRangeProbab=0.050000001;
			midRange=400;
			midRangeProbab=0.60000002;
			maxRange=600;
			maxRangeProbab=0.1;
		};
		class far: close
		{
			burst=3;
			aiRateOfFire=6;
			aiRateOfFireDistance=700;
			minRange=350;
			minRangeProbab=0.039999999;
			midRange=550;
			midRangeProbab=0.5;
			maxRange=700;
			maxRangeProbab=0.0099999998;
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"TFV_MA37_Smartlink_Scope"
				};
			};
			class PointerSlot: PointerSlot
			{
				compatibleitems[]={};
			};
		};
	};
	class TFV_MA37BGL: TFV_MA37GL
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		displayName="[TFV] MA40 + M301 GL Assault Rifle";
		model="\OPTRE_Weapons\AR\MA37BGL.p3d";
		baseWeapon="TFV_MA37BGL";
		magazines[]=
		{
			"TFV_32Rnd_762x51_Mag",
			"TFV_32Rnd_762x51_Mag_Tracer",
			"TFV_32Rnd_762x51_Mag_Tracer_Yellow"
		};
	};
	class TFV_MA32: TFV_MA37
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		model="\OPTRE_Weapons\AR\MA37I.p3d";
		displayName="[TFV] MA32 ICWS Assault Rifle";
		baseWeapon="TFV_MA32";
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"optic_Nightstalker",
					"optic_tws",
					"optic_tws_mg",
					"optic_NVS",
					"optic_DMS",
					"optic_LRPS",
					"optic_ams",
					"optic_AMS_snd",
					"optic_AMS_khk",
					"optic_KHS_blk",
					"optic_KHS_tan",
					"optic_KHS_hex",
					"optic_KHS_old",
					"optic_SOS",
					"optic_MRCO",
					"optic_Arco",
					"optic_aco",
					"optic_ACO_grn",
					"optic_aco_smg",
					"optic_ACO_grn_smg",
					"optic_hamr",
					"optic_Holosight",
					"optic_Holosight_smg",
					"optic_Hamr_khk_F",
					"optic_SOS_khk_F",
					"optic_Arco_ghex_F",
					"optic_Arco_blk_F",
					"optic_DMS_ghex_F",
					"optic_ERCO_blk_F",
					"optic_ERCO_khk_F",
					"optic_ERCO_snd_F",
					"optic_LRPS_ghex_F",
					"optic_LRPS_tna_F",
					"optic_Holosight_blk_F",
					"optic_Holosight_khk_F",
					"optic_Holosight_smg_blk_F",
					"optic_Holosight_smg_khk_F",
					"TFV_M392_Scope",
					"TFV_BR55HB_Scope",
					"TFV_M7_Sight",
					"TFV_M393_Scope",
					"TFV_M393_ACOG",
					"TFV_M393_EOTECH",
					"TFV_BR45_Scope"
				};
			};
		};
	};
	class TFV_MA32B: TFV_MA32
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		displayName="[TFV] MA40A ICWS Assault Rifle";
		model="\OPTRE_Weapons\AR\MA37BI.p3d";
		baseWeapon="TFV_MA32B";
		magazines[]=
		{
			"TFV_32Rnd_762x51_Mag",
			"TFV_32Rnd_762x51_Mag_Tracer",
			"TFV_32Rnd_762x51_Mag_Tracer_Yellow"
		};
	};
	class TFV_MA32GL: TFV_MA37GL
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		model="\OPTRE_Weapons\AR\MA37IGL.p3d";
		displayName="[TFV] MA32 + M301 GL Assault Rifle";
		baseWeapon="TFV_MA32GL";
		cursor="OPTRE_MA37";
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"optic_Nightstalker",
					"optic_tws",
					"optic_tws_mg",
					"optic_NVS",
					"optic_DMS",
					"optic_LRPS",
					"optic_ams",
					"optic_AMS_snd",
					"optic_AMS_khk",
					"optic_KHS_blk",
					"optic_KHS_tan",
					"optic_KHS_hex",
					"optic_KHS_old",
					"optic_SOS",
					"optic_MRCO",
					"optic_Arco",
					"optic_aco",
					"optic_ACO_grn",
					"optic_aco_smg",
					"optic_ACO_grn_smg",
					"optic_hamr",
					"optic_Holosight",
					"optic_Holosight_smg",
					"optic_Hamr_khk_F",
					"optic_SOS_khk_F",
					"optic_Arco_ghex_F",
					"optic_Arco_blk_F",
					"optic_DMS_ghex_F",
					"optic_ERCO_blk_F",
					"optic_ERCO_khk_F",
					"optic_ERCO_snd_F",
					"optic_LRPS_ghex_F",
					"optic_LRPS_tna_F",
					"optic_Holosight_blk_F",
					"optic_Holosight_khk_F",
					"optic_Holosight_smg_blk_F",
					"optic_Holosight_smg_khk_F",
					"TFV_M392_Scope",
					"TFV_BR55HB_Scope",
					"TFV_M7_Sight",
					"TFV_M393_Scope",
					"TFV_M393_ACOG",
					"TFV_M393_EOTECH",
					"TFV_BR45_Scope"
				};
			};
		};
	};
	class TFV_MA32BGL: TFV_MA32GL
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		displayName="[TFV] MA40A + M301 GL Assault Rifle";
		model="\OPTRE_Weapons\AR\MA37BIGL.p3d";
		baseWeapon="TFV_MA32BGL";
		cursor="OPTRE_MA37";
		magazines[]=
		{
			"TFV_32Rnd_762x51_Mag",
			"TFV_32Rnd_762x51_Mag_Tracer",
			"TFV_32Rnd_762x51_Mag_Tracer_Yellow"
		};
	};
	class TFV_MA5K: TFV_MA5C
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		displayName="[TFV] MA5K ICWS Carbine";
		handanim[]=
		{
			"OFP2_ManSkeleton",
			"\OPTRE_Weapons\ar\data\anim\hand_anim_ma5k.rtm",
			"Spartan_ManSkeleton",
			"\OPTRE_MJOLNIR\data\anims\OPTRE_anims\Weapons\ma5k_handanim_Spartan.rtm"
		};
		model="\OPTRE_Weapons\AR\MA5K.p3d";
		magazines[]=
		{
			"TFV_32Rnd_762x51_Mag",
			"TFV_32Rnd_762x51_Mag_Tracer",
			"TFV_32Rnd_762x51_Mag_UW",
			"TFV_32Rnd_762x51_Mag_Tracer_Yellow"
		};
		baseWeapon="TFV_MA5K";
		canShootInWater=1;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"OPTRE_Weapons\ar\data\ma5k_co.paa"
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=40;
			class CowsSlot: CowsSlot
			{
				compatibleitems[]=
				{
					"optic_Nightstalker",
					"optic_tws",
					"optic_tws_mg",
					"optic_NVS",
					"optic_DMS",
					"optic_LRPS",
					"optic_ams",
					"optic_AMS_snd",
					"optic_AMS_khk",
					"optic_KHS_blk",
					"optic_KHS_tan",
					"optic_KHS_hex",
					"optic_KHS_old",
					"optic_SOS",
					"optic_MRCO",
					"optic_Arco",
					"optic_aco",
					"optic_ACO_grn",
					"optic_aco_smg",
					"optic_ACO_grn_smg",
					"optic_hamr",
					"optic_Holosight",
					"optic_Holosight_smg",
					"optic_Hamr_khk_F",
					"optic_SOS_khk_F",
					"optic_Arco_ghex_F",
					"optic_Arco_blk_F",
					"optic_DMS_ghex_F",
					"optic_ERCO_blk_F",
					"optic_ERCO_khk_F",
					"optic_ERCO_snd_F",
					"optic_LRPS_ghex_F",
					"optic_LRPS_tna_F",
					"optic_Holosight_blk_F",
					"optic_Holosight_khk_F",
					"optic_Holosight_smg_blk_F",
					"optic_Holosight_smg_khk_F",
					"TFV_M392_Scope",
					"TFV_BR55HB_Scope",
					"TFV_M7_Sight",
					"TFV_M393_Scope",
					"TFV_M393_ACOG",
					"TFV_M393_EOTECH",
					"TFV_BR45_Scope"
				};
			};
		};
		class Single: Single
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-01.ogg",
					"db8",
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-02.ogg",
					"db8",
					1,
					2000
				};
				begin3[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-03.ogg",
					"db8",
					1,
					2000
				};
				begin4[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-04.ogg",
					"db8",
					1,
					2000
				};
				begin5[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-05.ogg",
					"db8",
					1,
					2000
				};
				begin6[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-06.ogg",
					"db8",
					1,
					2000
				};
				begin7[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-07.ogg",
					"db8",
					1,
					2000
				};
				begin8[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-08.ogg",
					"db8",
					1,
					2000
				};
				begin9[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-09.ogg",
					"db8",
					1,
					2000
				};
				begin10[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-10.ogg",
					"db8",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.1,
					"begin2",
					0.1,
					"begin3",
					0.1,
					"begin4",
					0.1,
					"begin5",
					0.1,
					"begin6",
					0.1,
					"begin7",
					0.1,
					"begin8",
					0.1,
					"begin9",
					0.1,
					"begin10",
					0.1
				};
			};
			reloadTime=0.075000003;
		};
		class FullAuto: FullAuto
		{
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class BaseSoundModeType
			{
				weaponSoundEffect="DefaultRifle";
				closure1[]={};
				closure2[]={};
				soundClosure[]=
				{
					"closure1",
					0.5,
					"closure2",
					0.5
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-01.ogg",
					"db8",
					1,
					2000
				};
				begin2[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-02.ogg",
					"db8",
					1,
					2000
				};
				begin3[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-03.ogg",
					"db8",
					1,
					2000
				};
				begin4[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-04.ogg",
					"db8",
					1,
					2000
				};
				begin5[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-05.ogg",
					"db8",
					1,
					2000
				};
				begin6[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-06.ogg",
					"db8",
					1,
					2000
				};
				begin7[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-07.ogg",
					"db8",
					1,
					2000
				};
				begin8[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-08.ogg",
					"db8",
					1,
					2000
				};
				begin9[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-09.ogg",
					"db8",
					1,
					2000
				};
				begin10[]=
				{
					"\OPTRE_Weapons\AR\Data\sounds\MA5K\MA5K-10.ogg",
					"db8",
					1,
					2000
				};
				soundBegin[]=
				{
					"begin1",
					0.1,
					"begin2",
					0.1,
					"begin3",
					0.1,
					"begin4",
					0.1,
					"begin5",
					0.1,
					"begin6",
					0.1,
					"begin7",
					0.1,
					"begin8",
					0.1,
					"begin9",
					0.1,
					"begin10",
					0.1
				};
			};
			reloadTime=0.075000003;
		};
	};
	class TFV_MA5B_AC: TFV_MA5B
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=1;
		scopeArsenal=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="TFV_MA5_SmartLink";
			};
		};
	};
	class TFV_MA5BGL_AC: TFV_MA5BGL
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=1;
		scopeArsenal=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="TFV_MA5_SmartLink";
			};
		};
	};
	class TFV_MA5C_AC: TFV_MA5C
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=1;
		scopeArsenal=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="TFV_MA5C_SmartLink";
			};
		};
	};
	class TFV_MA5CGL_AC: TFV_MA5CGL
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=1;
		scopeArsenal=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="TFV_MA5C_SmartLink";
			};
		};
	};
};
