class CfgPatches
{
	class TFV_Weapons_GL
	{
		units[]={};
		weapons[]=
		{
			"TFV_M319",
			"TFV_M319m",
			"TFV_M319n",
			"TFV_M319s"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"OPTRE_Core",
			"OPTRE_Weapons",
			"A3_Weapons_F"
		};
		author="Article 2 Studios";
	};
};
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class MuzzleSlot;
class CowsSlot;
class PointerSlot;
class UnderBarrelSlot;
class TFV_Handgun_Base;
class CfgWeapons
{
	class arifle_Mk20_F;
	class TFV_Rifle_Base: arifle_Mk20_F
	{
		class WeaponSlotsInfo;
	};
	class UGL_F;
	class TFV_M319: TFV_Rifle_Base
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		scopeArsenal=2;
		cursor="EmptyCursor";
		cursorAim="OPTRE_GRNDLNCH";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\OPTRE_Weapons\gl\data\anim\OPTRE_Handanim_M319.rtm",
			"Spartan_ManSkeleton",
			"\OPTRE_MJOLNIR\data\anims\OPTRE_anims\Weapons\m319_Spartan_HandAnim.rtm"
		};
		model="\OPTRE_Weapons\GL\M319.p3d";
		displayName="[TFV] M319 Individual Grenade Launcher";
		descriptionShort="Grenade Launcher";
		magazineWell[]={};
		baseWeapon="TFV_M319";
		muzzlePos="usti hlavne";
		muzzleEnd="konec hlavne";
		useModelOptics=0;
		useExternalOptic=0;
		cameraDir="OP_look";
		memoryPointCamera="OP_eye";
		discreteDistance[]={100,200,300};
		discreteDistanceCameraPoint[]=
		{
			"OP_eye",
			"OP_eye2"
		};
		discreteDistanceInitIndex=0;
		reloadAction="ReloadMagazine";
		changeFiremodeSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Firemode_ugl",
			0.31622776,
			1,
			5
		};
		reloadMagazineSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Reload_UGL",
			0.56234133,
			1,
			10
		};
		drySound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Dry_ugl",
			0.56234133,
			1,
			10
		};
		modes[]=
		{
			"Single"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\Closure_UGL",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					1
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\UGL_01",
					0.70794576,
					1,
					200
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\UGL_02",
					0.70794576,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			recoil="M240Recoil";
			recoilProne="M240Recoil";
			minRange=30;
			minRangeProbab=0.1;
			midRange=200;
			midRangeProbab=0.69999999;
			maxRange=400;
			maxRangeProbab=0.050000001;
		};
		recoil="recoil_default";
		magazineReloadTime=0;
		reloadTime=0.1;
		optics=1;
		modelOptics="-";
		magazines[]=
		{
			"M319_HE_Grenade_Shell",
			"M319_HEDP_Grenade_Shell",
			"M319_Buckshot",
			"M319_Smoke",
			"M319_Smoke_Orange",
			"M319_Smoke_Green",
			"M319_Smoke_Red",
			"1Rnd_HE_Grenade_shell",
			"UGL_FlareWhite_F",
			"UGL_FlareGreen_F",
			"UGL_FlareRed_F",
			"UGL_FlareYellow_F",
			"UGL_FlareCIR_F",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_UGL_FlareWhite_F",
			"3Rnd_UGL_FlareGreen_F",
			"3Rnd_UGL_FlareRed_F",
			"3Rnd_UGL_FlareYellow_F",
			"3Rnd_UGL_FlareCIR_F",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_SmokeRed_Grenade_shell",
			"3Rnd_SmokeGreen_Grenade_shell",
			"3Rnd_SmokeYellow_Grenade_shell",
			"3Rnd_SmokePurple_Grenade_shell",
			"3Rnd_SmokeBlue_Grenade_shell",
			"3Rnd_SmokeOrange_Grenade_shell"
		};
		class GunParticles
		{
		};
		class WeaponSlotsInfo
		{
			mass=50;
		};
	};
	class TFV_M319n: TFV_Rifle_Base
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		cursor="EmptyCursor";
		cursorAim="OPTRE_GRNDLNCH";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\OPTRE_Weapons\gl\data\anim\OPTRE_Handanim_M319N.rtm",
			"Spartan_ManSkeleton",
			"\OPTRE_MJOLNIR\data\anims\OPTRE_anims\Weapons\m319_Spartan_HandAnim.rtm"
		};
		model="\OPTRE_Weapons\GL\M319N.p3d";
		displayName="[TFV] M319N Individual Grenade Launcher";
		descriptionShort="Grenade Launcher";
		magazineWell[]={};
		baseWeapon="TFV_M319n";
		muzzlePos="usti hlavne";
		muzzleEnd="konec hlavne";
		useModelOptics=0;
		useExternalOptic=0;
		cameraDir="OP_look";
		memoryPointCamera="OP_eye";
		discreteDistance[]={100,200,300};
		discreteDistanceCameraPoint[]=
		{
			"OP_eye"
		};
		discreteDistanceInitIndex=0;
		reloadAction="ReloadMagazine";
		changeFiremodeSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Firemode_ugl",
			0.31622776,
			1,
			5
		};
		reloadMagazineSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Reload_UGL",
			0.56234133,
			1,
			10
		};
		drySound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Dry_ugl",
			0.56234133,
			1,
			10
		};
		modes[]=
		{
			"Single"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\Closure_UGL",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					1
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\UGL_01",
					0.70794576,
					1,
					200
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\UGL_02",
					0.70794576,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			recoil="M240Recoil";
			recoilProne="M240Recoil";
			minRange=30;
			minRangeProbab=0.1;
			midRange=200;
			midRangeProbab=0.69999999;
			maxRange=400;
			maxRangeProbab=0.050000001;
		};
		recoil="recoil_default";
		magazineReloadTime=0;
		reloadTime=0.1;
		optics=1;
		modelOptics="-";
		magazines[]=
		{
			"M319_HE_Grenade_Shell",
			"M319_HEDP_Grenade_Shell",
			"M319_Buckshot",
			"M319_Smoke",
			"M319_Smoke_Orange",
			"M319_Smoke_Green",
			"M319_Smoke_Red",
			"1Rnd_HE_Grenade_shell",
			"UGL_FlareWhite_F",
			"UGL_FlareGreen_F",
			"UGL_FlareRed_F",
			"UGL_FlareYellow_F",
			"UGL_FlareCIR_F",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_UGL_FlareWhite_F",
			"3Rnd_UGL_FlareGreen_F",
			"3Rnd_UGL_FlareRed_F",
			"3Rnd_UGL_FlareYellow_F",
			"3Rnd_UGL_FlareCIR_F",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_SmokeRed_Grenade_shell",
			"3Rnd_SmokeGreen_Grenade_shell",
			"3Rnd_SmokeYellow_Grenade_shell",
			"3Rnd_SmokePurple_Grenade_shell",
			"3Rnd_SmokeBlue_Grenade_shell",
			"3Rnd_SmokeOrange_Grenade_shell"
		};
		class GunParticles
		{
		};
		class WeaponSlotsInfo
		{
			mass=50;
		};
	};
	class TFV_M319m: TFV_Handgun_Base
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		model="\OPTRE_Weapons\GL\M319m.p3d";
		displayName="[TFV] M319M Hand Grenade Launcher";
		descriptionShort="Grenade Launcher";
		cursor="EmptyCursor";
		cursorAim="OPTRE_GRNDLNCH";
		magazineWell[]={};
		baseWeapon="TFV_M319m";
		muzzlePos="usti hlavne";
		muzzleEnd="konec hlavne";
		useModelOptics=0;
		useExternalOptic=0;
		cameraDir="OP_look";
		memoryPointCamera="OP_eye";
		discreteDistance[]={100};
		discreteDistanceCameraPoint[]=
		{
			"OP_eye"
		};
		discreteDistanceInitIndex=0;
		reloadAction="ReloadMagazine";
		changeFiremodeSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Firemode_ugl",
			0.31622776,
			1,
			5
		};
		reloadMagazineSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Reload_UGL",
			0.56234133,
			1,
			10
		};
		drySound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Dry_ugl",
			0.56234133,
			1,
			10
		};
		modes[]=
		{
			"Single"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\Closure_UGL",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					1
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\UGL_01",
					0.70794576,
					1,
					200
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\UGL_02",
					0.70794576,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			recoil="M240Recoil";
			recoilProne="M240Recoil";
			minRange=30;
			minRangeProbab=0.1;
			midRange=200;
			midRangeProbab=0.69999999;
			maxRange=400;
			maxRangeProbab=0.050000001;
		};
		recoil="recoil_default";
		magazineReloadTime=0;
		reloadTime=0.1;
		optics=1;
		modelOptics="-";
		magazines[]=
		{
			"M319_HE_Grenade_Shell",
			"M319_HEDP_Grenade_Shell",
			"M319_Buckshot",
			"M319_Smoke",
			"M319_Smoke_Orange",
			"M319_Smoke_Green",
			"M319_Smoke_Red",
			"1Rnd_HE_Grenade_shell",
			"UGL_FlareWhite_F",
			"UGL_FlareGreen_F",
			"UGL_FlareRed_F",
			"UGL_FlareYellow_F",
			"UGL_FlareCIR_F",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_UGL_FlareWhite_F",
			"3Rnd_UGL_FlareGreen_F",
			"3Rnd_UGL_FlareRed_F",
			"3Rnd_UGL_FlareYellow_F",
			"3Rnd_UGL_FlareCIR_F",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_SmokeRed_Grenade_shell",
			"3Rnd_SmokeGreen_Grenade_shell",
			"3Rnd_SmokeYellow_Grenade_shell",
			"3Rnd_SmokePurple_Grenade_shell",
			"3Rnd_SmokeBlue_Grenade_shell",
			"3Rnd_SmokeOrange_Grenade_shell"
		};
		class GunParticles
		{
		};
		class WeaponSlotsInfo
		{
			mass=50;
		};
	};
	class TFV_M319s: TFV_Handgun_Base
	{
		dlc="OPTRE";
		author="Article 2 Studios";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		model="\OPTRE_Weapons\GL\M319s.p3d";
		displayName="[TFV] M319S Signal Flare Launcher";
		descriptionShort="Grenade Launcher";
		cursor="EmptyCursor";
		cursorAim="OPTRE_GRNDLNCH";
		magazineWell[]={};
		baseWeapon="TFV_M319s";
		muzzlePos="usti hlavne";
		muzzleEnd="konec hlavne";
		useModelOptics=0;
		useExternalOptic=0;
		cameraDir="OP_look";
		memoryPointCamera="OP_eye";
		discreteDistance[]={100};
		discreteDistanceCameraPoint[]=
		{
			"OP_eye"
		};
		discreteDistanceInitIndex=0;
		reloadAction="ReloadMagazine";
		changeFiremodeSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Firemode_ugl",
			0.31622776,
			1,
			5
		};
		reloadMagazineSound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Reload_UGL",
			0.56234133,
			1,
			10
		};
		drySound[]=
		{
			"A3\Sounds_F\arsenal\weapons\UGL\Dry_ugl",
			0.56234133,
			1,
			10
		};
		modes[]=
		{
			"Single"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType
			{
				closure1[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\Closure_UGL",
					1,
					1,
					10
				};
				soundClosure[]=
				{
					"closure1",
					1
				};
			};
			class StandardSound: BaseSoundModeType
			{
				begin1[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\UGL_01",
					0.70794576,
					1,
					200
				};
				begin2[]=
				{
					"A3\Sounds_F\arsenal\weapons\UGL\UGL_02",
					0.70794576,
					1,
					200
				};
				soundBegin[]=
				{
					"begin1",
					0.5,
					"begin2",
					0.5
				};
			};
			recoil="M240Recoil";
			recoilProne="M240Recoil";
			minRange=30;
			minRangeProbab=0.1;
			midRange=200;
			midRangeProbab=0.69999999;
			maxRange=400;
			maxRangeProbab=0.050000001;
		};
		recoil="recoil_default";
		magazineReloadTime=0;
		reloadTime=0.1;
		optics=1;
		modelOptics="-";
		magazines[]=
		{
			"1Rnd_HE_Grenade_shell",
			"UGL_FlareWhite_F",
			"UGL_FlareGreen_F",
			"UGL_FlareRed_F",
			"UGL_FlareYellow_F",
			"UGL_FlareCIR_F",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell",
			"1Rnd_SmokePurple_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_UGL_FlareWhite_F",
			"3Rnd_UGL_FlareGreen_F",
			"3Rnd_UGL_FlareRed_F",
			"3Rnd_UGL_FlareYellow_F",
			"3Rnd_UGL_FlareCIR_F",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_SmokeRed_Grenade_shell",
			"3Rnd_SmokeGreen_Grenade_shell",
			"3Rnd_SmokeYellow_Grenade_shell",
			"3Rnd_SmokePurple_Grenade_shell",
			"3Rnd_SmokeBlue_Grenade_shell",
			"3Rnd_SmokeOrange_Grenade_shell",
			"M319_HE_Grenade_Shell",
			"M319_Buckshot",
			"M319_Smoke",
			"M319_Smoke_Orange",
			"M319_Smoke_Green",
			"M319_Smoke_Red"
		};
		class GunParticles
		{
		};
		class WeaponSlotsInfo
		{
			mass=50;
		};
	};
};
